[package]
name = "wayland-kbd"
version = "0.2.1"
documentation = "http://vberger.github.io/wayland-kbd/wayland_kbd/"
repository = "https://github.com/vberger/wayland-kbd"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Keyboard mapping utility for wayland-client using libxkbcommon."

[dependencies]
bitflags = "0.3"
lazy_static = "0.1"
libc = "0.1"
mmap = "0.1"
wayland-client = "^0.2.0"
dlib = "^0.1.1"

[dev-dependencies]
wayland-client = { features = ["dlopen"] }
